server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(promtail|loki|mimir|tempo|prometheus|grafana|postgres-exporter|redis-exporter|node-exporter)"
        action: drop
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(iam-service|merchant-service|catalog-service|backoffice|caddy|postgres|redis|minio)"
        action: keep
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "service"
        replacement: "${1}"
      - source_labels: ["__meta_docker_container_log_stream"]
        target_label: "stream"
      - source_labels: ["__meta_docker_container_label_com_docker_compose_service"]
        target_label: "service"

  - job_name: services
    static_configs:
      - targets: ["localhost"]
        labels:
          job: pos-services
          __path__: /logs/*.log
