- name: Provision development server
  hosts: all
  become: yes
  vars_files:
    - ../vars/vault.yml
  tasks:
    - name: Install Docker
      ansible.builtin.import_role:
        name: docker

    - name: Run PostgreSQL
      ansible.builtin.import_role:
        name: postgres
      vars:
        postgres_password: "{{ vault_postgres_password }}"

    - name: Run Redis
      ansible.builtin.import_role:
        name: redis

    - name: Run LGTM stack
      ansible.builtin.import_role:
        name: lgtm

    - name: Deploy Traefik reverse proxy
      ansible.builtin.import_role:
        name: traefik
