name: pos_mobile
description: "POS Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.0
  flutter_riverpod: ^2.5.0
  sqflite: ^2.3.0
  path: ^1.8.0
  dio: ^5.4.0
  connectivity_plus: ^7.3.0
  mobile_scanner: 7.2.0
  flutter_secure_storage: ^9.2.0
  uuid: ^4.2.0
  intl: ^0.20.2
  decimal: ^2.3.0
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
