# Resolve all *.saleforges.local to localhost
address=/saleforges.local/127.0.0.1

# Listen only on localhost
bind-interfaces
listen-address=127.0.0.1
port=53

# Forward upstream queries to network DNS
server=172.30.251.26
server=103.180.58.54

# No DNS caching for local dev
cache-size=0
